[jvlink]
executable = "C:/JVLinkToSQLite/JVLinkToSQLite.exe"
seed_setting = "C:/JVLinkToSQLite/setting.xml"

# Optional target race for `--retrieve --mode=realtime`.
# [realtime]
# date = 2026-10-04
# jyo = "05"
# kaiji = "04"
# nichiji = "08"
# race = "11"

[historical]
normal_update = false
setup_update = false
realtime_update = false
normal_data_specs = []
setup_data_specs = [
  "RACE",
  "DIFF",
  "BLOD",
  "SNAP",
  "SLOP",
  "WOOD",
  "YSCH",
  "HOSE",
  "HOYU",
  "COMM",
  "MING",
  "DIFN",
  "BLDN",
  "SNPN",
  "HOSN",
]
realtime_data_specs = []

[historical.start_datetimes]
RACE = 1986-01-01T00:00:00
DIFF = 1986-01-01T00:00:00
BLOD = 1986-01-01T00:00:00
SNAP = 2004-01-01T00:00:00
SLOP = 2003-01-01T00:00:00
WOOD = 2021-07-27T00:00:00
YSCH = 2000-01-01T00:00:00
HOSE = 1997-01-01T00:00:00
HOYU = 2000-01-01T00:00:00
COMM = 1986-01-01T00:00:00
MING = 2001-09-01T00:00:00
DIFN = 2023-08-08T00:00:00
BLDN = 2023-08-08T00:00:00
SNPN = 2004-01-01T00:00:00
HOSN = 2023-08-08T00:00:00

[historical_odds]
normal_update = false
setup_update = false
realtime_update = true
normal_data_specs = []
setup_data_specs = []
realtime_data_specs = ["0B41", "0B42"]
race_start_date = 2003-10-04
skip_existing = true

[latest]
normal_update = true
setup_update = false
realtime_update = true
normal_data_specs = ["RACE"]
setup_data_specs = []
realtime_data_specs = ["0B12", "0B15", "0B11", "0B14", "0B13", "0B17"]

[realtime_history]
normal_update = false
setup_update = false
realtime_update = true
normal_data_specs = []
setup_data_specs = []
realtime_data_specs = ["0B41", "0B42"]

[realtime_current]
normal_update = false
setup_update = false
realtime_update = true
normal_data_specs = []
setup_data_specs = []
realtime_data_specs = ["0B31", "0B32"]
